name: noveler
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2　
  share_plus: ^4.4.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  app_tracking_transparency: ^2.0.3
  riverpod: ^2.3.2
  flutter_riverpod: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^1.0.0

flutter_icons:
  image_path: "lib/assets/noveler_book.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

